apiVersion: v1
kind: Pod

metadata:
  name: ace-pod
  labels:
    app: ace

spec:
  containers:
    - name: ace
      image: ace_image:IMAGE_TAG
      imagePullPolicy: Never

      ports:
        - containerPort: 3000
