apiVersion: v1
kind: Pod

metadata:
  name: ace-pod
  labels:
    app: ace

spec:
  containers:
    - name: ace
      image: IMAGE_URI
      imagePullPolicy: Always

      ports:
        - containerPort: 3000
