apiVersion: v1
kind: Service

metadata:
  name: ace-service

spec:
  type: NodePort

  selector:
    app: ace

  ports:
    - protocol: TCP
      port: 80
      targetPort: 2075
      nodePort: 30080
